import { createFileRoute } from "@tanstack/react-router";
import { Expand } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { PageHero, ContactBand } from "@/components/site/shared";
import classroom from "@/assets/classroom-training.jpg.asset.json";
import programming from "@/assets/programming-session.jpg.asset.json";
import cloud from "@/assets/cloud-lab.jpg.asset.json";
import student from "@/assets/knowledge-hub-student.jpg.asset.json";
const images=[{src:classroom.url,alt:"Instructor assisting learners in the computer lab",title:"Guided lab training"},{src:programming.url,alt:"Students learning programming with an instructor",title:"Programming practice"},{src:cloud.url,alt:"Cloud computing class at Knowledge Hub",title:"Cloud learning session"},{src:student.url,alt:"Student working confidently on a laptop",title:"Focused individual learning"},{src:programming.url,alt:"Small group discussing code during class",title:"Collaborative learning"},{src:classroom.url,alt:"Students completing practical computer exercises",title:"Hands-on classroom"}];
export const Route=createFileRoute("/gallery")({head:()=>({meta:[{title:"Training Gallery | Knowledge Hub Suncity"},{name:"description",content:"See practical classroom learning, programming sessions, and computer lab training at Knowledge Hub."},{property:"og:title",content:"Knowledge Hub Training Gallery"},{property:"og:description",content:"A look inside our practical, supportive learning environment."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:GalleryPage});
function GalleryPage(){const [selected,setSelected]=useState<(typeof images)[number]|null>(null);return <><PageHero eyebrow="Inside Knowledge Hub" title="A closer look at learning in action." copy="Practical sessions, instructor guidance, and focused practice form the heart of the Knowledge Hub experience."/><section className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 sm:grid-cols-2 lg:grid-cols-3">{images.map((img,i)=><button key={`${img.title}-${i}`} onClick={()=>setSelected(img)} className="group relative aspect-[4/3] cursor-pointer overflow-hidden rounded-2xl text-left shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><img src={img.src} alt={img.alt} width={1280} height={960} loading="lazy" className="size-full object-cover transition-transform duration-700 ease-in-out group-hover:scale-105"/><span className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-gallery-overlay p-5 text-gallery-foreground"><strong className="font-display text-sm">{img.title}</strong><Expand className="size-5"/></span></button>)}</div></section><Dialog open={Boolean(selected)} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="max-w-5xl border-0 bg-transparent p-3 shadow-none"><DialogTitle className="sr-only">{selected?.title}</DialogTitle><DialogDescription className="sr-only">Expanded gallery image</DialogDescription>{selected&&<img src={selected.src} alt={selected.alt} className="max-h-[82vh] w-full rounded-xl object-contain"/>}</DialogContent></Dialog><ContactBand/></>}
